name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          go get -v -t $(go list ./... | grep -v /examples)
          go mod tidy

      - name: Build gscloud
        run: make

      - name: Lint gscloud
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.2
          make lint

      - name: Run tests
        run: make test
